public class Main {
    
    public static void main(String[] args) {

        // Charstream from the second LZW Example from moodle
//        String charstream = "ABBABCABABBABACB";

        // Charstream from the third LZW Example from moodle
//        String charstream = "AAAAAAAABBBBACCAAAAAAAABDDDBBCAAAAAAAABDDDBBDBAAAAAAABDBBBCCDBBAAAACBDDBBCCBDDCAAABDDDBBDBBDDBCAABDDBBBBBEEEBBCACDBBBBBBBEFEBCAACDBBBBBBEFCFEAAACDBBBBBBEFCFEAAACBBBBBBEFFCFFEAACGGBBBEFFFFFFFEACGGGBBEFFFCFFFEAACGGCEFFFFFFFFFEAACCCEEEEEEEEEEEAAAAAAAAAAAAAAAA";

        // Charstream from assignment question
        String charstream = "AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBAABAAAAAAAAAAAABAABAAAAAAAAAAAABAABBBBBBBBBBBBBBAABBBBBBCCBDBBBBAABBBBBCDDCABBBBAABBBBCDEEDCBBBBAABBBCDEAAEDCBBBAABBCDEEEEEEDCBBAABBBDEDCCDEDBBBAABBBDECCCCEDBBBAABBCDECCCCEDCBBAABBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAFFFFFFFFFFFFFFFF";

        Encoder encoder = new Encoder(charstream);
        encoder.startEncoding();

    }
}
